# TA-Lib

In [1]:
import talib
import numpy as np

ModuleNotFoundError: No module named 'talib'

模擬 180 天的股市資料

In [13]:
import pandas as pd
import numpy as np
import openpyxl

# 設定隨機數種子以保持數據的一致性
np.random.seed(0)

# 模擬 180 天的股市資料
dates = pd.date_range(start="2023-01-01", periods=180, freq='B')  # 僅包含工作日
open_prices = np.random.uniform(low=100, high=200, size=len(dates))
high_prices = open_prices + np.random.uniform(low=0, high=10, size=len(dates))
low_prices = open_prices - np.random.uniform(low=0, high=10, size=len(dates))
close_prices = np.random.uniform(low=low_prices, high=high_prices)

# 建立 DataFrame
stock_data = pd.DataFrame({
    'Date': dates,
    'Open': open_prices,
    'High': high_prices,
    'Low': low_prices,
    'Close': close_prices
})

# 將日期設置為索引
stock_data.set_index('Date', inplace=True)

# 儲存數據到 Excel 文件
excel_file_path = 'stock_data.xlsx'  # 您可以更改路徑
stock_data.to_excel(excel_file_path)

print(f"股市資料已儲存到 {excel_file_path}")


股市資料已儲存到 stock_data.xlsx


close_prices 是一個包含收盤價的 NumPy 數組

In [14]:
# 首先讀取剛才儲存的 Excel 文件
stock_data_read = pd.read_excel('stock_data.xlsx', index_col=0)

# 從讀取的數據中提取收盤價
close_prices = np.array(stock_data_read['Close'])

# 展示一部分收盤價數據
# close_prices[:10]  # 顯示前 10 個收盤價


In [15]:
# 計算 30 日簡單移動平均線
moving_average = talib.SMA(close_prices, timeperiod=30)
moving_average

array([         nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan, 158.43190247, 157.84839147, 157.88379677,
       157.31947319, 157.27519989, 155.64280771, 155.54754008,
       155.99581762, 155.04424085, 155.08603075, 156.44490216,
       154.86925176, 154.74219191, 155.30902207, 152.09190234,
       153.88620701, 155.82966515, 156.55577458, 154.29525682,
       152.62527681, 151.05156025, 149.79609565, 148.7446134 ,
       150.49236609, 148.16813096, 148.57183145, 147.12040981,
       148.83897211, 146.46942605, 146.18259435, 145.51730987,
       144.64566289, 142.35745521, 143.13099584, 141.78

指數移動平均（EMA）

In [16]:
EMA = talib.EMA(close_prices, timeperiod=30)
EMA

array([         nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan, 158.43190247, 156.95334244, 158.0153202 ,
       157.15234308, 156.86390759, 153.32815022, 153.58609558,
       153.91858359, 154.61328781, 157.34214841, 158.51725315,
       156.90897588, 156.22602491, 157.14111009, 153.31929412,
       154.09420027, 154.86250669, 152.49544327, 149.80760111,
       148.29434518, 147.95114737, 148.65481248, 148.44087114,
       151.90273904, 149.14471897, 147.26318987, 145.52775782,
       146.83758962, 145.58660056, 145.67541119, 144.66820066,
       142.39056272, 139.9632856 , 141.7621313 , 139.86

相對強弱指數（RSI）

In [17]:
RSI = talib.RSI(close_prices, timeperiod=14)
RSI

array([        nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan, 44.53590331,
       44.06105033, 42.60581528, 54.40226279, 54.08241548, 55.83005616,
       56.64968748, 53.34526121, 49.07319337, 53.38817866, 43.69635505,
       51.22162447, 45.42983242, 54.77830678, 50.06821806, 49.47684476,
       47.88352811, 52.21290769, 48.89205472, 49.8520815 , 44.22136381,
       50.76027088, 50.91873335, 51.62417053, 55.36762252, 52.46998058,
       47.23774361, 48.90277233, 51.98898069, 43.47626088, 51.43937624,
       51.5127586 , 46.16975212, 45.39175561, 47.40969564, 49.55984525,
       51.59624929, 49.75495466, 56.73592737, 45.57055042, 46.8819684 ,
       46.93067347, 52.49914546, 47.92712699, 50.29725514, 48.24929488,
       45.79003455, 45.23854193, 53.51206074, 46.8138552 , 47.96797144,
       49.85529822, 54.71848983, 46.64594538, 54.34526011, 47.02

隨機指標（Stochastic Oscillator）

In [18]:
slowk, slowd = talib.STOCH(high, low, close, fastk_period=5, slowk_period=3, slowk_matype=0, slowd_period=3, slowd_matype=0)

NameError: name 'high' is not defined

平均方向性指數（ADX）

In [ ]:
ADX = talib.ADX(high, low, close, timeperiod=14)

布林帶（Bollinger Bands）

In [ ]:
upperband, middleband, lowerband = talib.BBANDS(close, timeperiod=20, nbdevup=2, nbdevdn=2, matype=0)