# TA-Lib

In [1]:
import talib
import numpy as np

# 模擬 360 天的股市資料

In [15]:
import pandas as pd
import numpy as np
import openpyxl
import datetime

# 設定隨機數種子以保持數據一致性
np.random.seed(0)

# 模擬 360 天的股市資料，僅包含工作日
dates = pd.date_range(
    start="2024-01-01", periods=360, freq='B'
)

# 產生股市數據
open_prices = np.random.uniform(low=100, high=200, size=len(dates))
high_prices = open_prices + np.random.uniform(low=0, high=10, size=len(dates))
low_prices = open_prices - np.random.uniform(low=0, high=10, size=len(dates))
close_prices = np.random.uniform(low=low_prices, high=high_prices)

# 建立 DataFrame
stock_data = pd.DataFrame({
    # 只保留 "YYYY-MM-DD"
    'Date': dates.strftime('%Y-%m-%d'),
    'Open': open_prices,
    'High': high_prices,
    'Low': low_prices,
    'Close': close_prices
})

# 設定存檔名稱 (使用日期範圍作為尾綴)
start_date = stock_data['Date'].iloc[0].replace('-', '')
end_date = stock_data['Date'].iloc[-1].replace('-', '')
excel_file_path = f'data/股市資料_{start_date}-{end_date}.xlsx'

# 儲存數據到 Excel (設定 sheet 名稱)
with pd.ExcelWriter(excel_file_path, engine='openpyxl') as writer:
    stock_data.to_excel(
        writer, index=False, sheet_name="Stock Data"
    )

print(f"股市資料已儲存到 {excel_file_path}")


股市資料已儲存到 data/股市資料_20240101-20250516.xlsx


close_prices 是一個包含收盤價的 NumPy 數組

In [ ]:
# 首先讀取剛才儲存的 Excel 文件
stock_data_read = pd.read_excel(excel_file_path, index_col=0)

# 從讀取的數據中提取收盤價
close_prices = np.array(stock_data_read['Close'])

# 顯示前 10 個收盤價
close_prices[:10]


array([151.1042175 , 176.42944723, 160.79415804, 158.61564274,
       149.41575373, 164.0636148 , 137.45797554, 189.02029356,
       203.96435514, 140.23073615])

計算移動平均

In [17]:
# 計算 30 日簡單移動平均線
moving_average = talib.SMA(close_prices, timeperiod=30)
moving_average

array([         nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan, 159.65870176, 158.76149153, 158.74891421,
       158.07452181, 157.91659796, 156.28718252, 156.07891441,
       156.87322456, 155.96606381, 155.64360301, 156.60623881,
       155.13659705, 155.16883146, 155.46655248, 152.33951253,
       154.54047093, 156.65010582, 157.47390421, 154.82182047,
       152.94592798, 151.06968524, 149.40989643, 148.05232592,
       149.74374578, 147.32411651, 147.29548781, 145.4218723 ,
       147.15489839, 145.02904972, 144.75365017, 144.32767287,
       144.0450915 , 141.92097418, 142.5680233 , 141.18

指數移動平均（EMA）

In [5]:
EMA = talib.EMA(close_prices, timeperiod=30)
EMA

array([         nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan, 159.07695668, 156.70179925, 158.25509665,
       157.71520716, 157.09568019, 153.36349758, 153.89522468,
       154.59899377, 155.44731077, 158.28908436, 158.88392649,
       157.35934786, 156.71039596, 157.25777761, 153.64763579,
       154.7788877 , 155.37997553, 153.49414128, 150.95471095,
       149.61727151, 148.85104509, 149.75527913, 149.43756813,
       152.81863679, 150.11161506, 147.8196087 , 145.8005391 ,
       146.87961853, 145.25032031, 145.67222008, 144.83822122,
       143.06331061, 140.97233324, 142.58691904, 141.01

相對強弱指數（RSI）

In [6]:
RSI = talib.RSI(close_prices, timeperiod=14)
RSI

array([        nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan, 44.65981646,
       44.33398279, 43.40299526, 55.18347358, 53.80844189, 56.21979079,
       56.85529752, 53.74916989, 48.03781216, 53.27316104, 44.19762871,
       51.32658612, 45.20264643, 54.44396643, 49.16543865, 48.99187917,
       46.68934073, 52.8058057 , 49.5723273 , 49.38527765, 44.41463428,
       51.16902585, 51.49458906, 51.81308243, 55.22687506, 51.28471084,
       47.59503561, 49.06889783, 51.26146307, 43.98086826, 52.00909783,
       51.20767778, 47.02863096, 45.75518799, 47.7938149 , 48.76246201,
       51.97057601, 49.57123325, 56.42044808, 45.74311619, 46.19217119,
       46.4405557 , 52.09226116, 47.31199628, 50.89118187, 48.64436785,
       46.8413494 , 46.04575305, 53.15195096, 47.35670838, 47.59416146,
       50.14005261, 55.27822245, 45.96903706, 54.19632386, 47.30

隨機指標（Stochastic Oscillator）

In [11]:
df = pd.read_excel(excel_file_path)

# 確保欄位名稱正確
print(df.head())

# 確保 `high`, `low`, `close` 欄位正確讀取
high = df["High"].values.astype(np.float64)
low = df["Low"].values.astype(np.float64)
close = df["Close"].values.astype(np.float64)

# 確保 `high`, `low`, `close` 已正確轉換為 NumPy 陣列
print(f"High: {high[:5]}")
print(f"Low: {low[:5]}")
print(f"Close: {close[:5]}")

# 計算 STOCH 隨機指標
slowk, slowd = talib.STOCH(
    high, low, close,
    fastk_period=5,
    slowk_period=3, slowk_matype=0,
    slowd_period=3, slowd_matype=0
)

# 轉換回 DataFrame 方便檢視
df["SlowK"] = slowk
df["SlowD"] = slowd

# 顯示最後 10 筆數據
print(df.tail(10))

# 儲存結果到 Excel
output_file = "data/股市資料_STOCH.xlsx"
df.to_excel(output_file, index=False)
print(f"結果已儲存到 {output_file}")


         Date        Open        High         Low       Close
0  2024-01-01  154.881350  157.985159  148.952548  152.988258
1  2024-01-02  171.518937  175.249285  171.418300  174.624798
2  2024-01-03  160.276338  165.526042  155.518076  157.738083
3  2024-01-04  154.488318  161.994269  147.400614  154.609081
4  2024-01-05  142.365480  145.700555  141.925726  145.434877
High: [157.98515865 175.24928528 165.52604203 161.99426853 145.70055459]
Low: [148.95254768 171.41829968 155.51807565 147.40061439 141.92572561]
Close: [152.98825793 174.62479771 157.73808309 154.60908061 145.43487737]
           Date        Open        High         Low       Close      SlowK  \
490  2025-11-17  127.482357  127.604069  123.699679  124.375893  47.130601   
491  2025-11-18  159.223042  162.451337  152.644421  161.227430  31.240942   
492  2025-11-19  189.676116  191.971790  186.081584  186.244467  44.647364   
493  2025-11-20  140.673335  145.741964  131.669660  140.962146  52.775963   
494  2025-11-21  15

平均方向性指數（ADX）

In [12]:
ADX = talib.ADX(high, low, close, timeperiod=14)

布林帶（Bollinger Bands）

In [13]:
upperband, middleband, lowerband = talib.BBANDS(close, timeperiod=20, nbdevup=2, nbdevdn=2, matype=0)

In [14]:
import pandas as pd
import numpy as np
import talib

# 讀取 Excel 檔案
df = pd.read_excel(excel_file_path)

# 確保欄位名稱正確
print(df.head())

# 轉換數據格式為 NumPy 陣列，避免 `TA-Lib` 無法運行
high = df["High"].values.astype(np.float64)
low = df["Low"].values.astype(np.float64)
close = df["Close"].values.astype(np.float64)

# 計算 ADX，趨勢強度指標
df["ADX"] = talib.ADX(high, low, close, timeperiod=14)
# 計算 BBANDS，布林通道
df["UpperBand"], df["MiddleBand"], df["LowerBand"] = talib.BBANDS(
    close, timeperiod=20, nbdevup=2, nbdevdn=2, matype=0
)
# 顯示最後 10 筆數據
print(df.tail(10))
# 儲存結果到 Excel
output_file = "data/股市資料_帶ADX_BBANDS.xlsx"
df.to_excel(output_file, index=False)
print(f"結果已儲存到 {output_file}")

         Date        Open        High         Low       Close
0  2024-01-01  154.881350  157.985159  148.952548  152.988258
1  2024-01-02  171.518937  175.249285  171.418300  174.624798
2  2024-01-03  160.276338  165.526042  155.518076  157.738083
3  2024-01-04  154.488318  161.994269  147.400614  154.609081
4  2024-01-05  142.365480  145.700555  141.925726  145.434877
           Date        Open        High         Low       Close       ADX  \
490  2025-11-17  127.482357  127.604069  123.699679  124.375893  6.220941   
491  2025-11-18  159.223042  162.451337  152.644421  161.227430  5.819857   
492  2025-11-19  189.676116  191.971790  186.081584  186.244467  5.960156   
493  2025-11-20  140.673335  145.741964  131.669660  140.962146  5.943722   
494  2025-11-21  155.207828  162.576359  145.375079  152.503958  5.625620   
495  2025-11-24  127.165277  128.142040  126.861012  127.874666  5.649272   
496  2025-11-25  145.544415  150.693637  143.608182  148.718199  5.246366   
497  2025-11