# Numpy

## 建立基本陣列

In [ ]:
import numpy as np
np1 = np.array([1,2,3,4])		#使用list
np2 = np.array((5,6,7,8))		#使用tuple
print(np1)
print(np2)
print(type(np1), type(np2))

[1 2 3 4]
[5 6 7 8]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [ ]:
import numpy as np
na = np.arange(0, 31, 2)
print(na)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]


In [ ]:
import numpy as np
na = np.linspace(1, 15, 3)
print(na)

[ 1.  8. 15.]


In [ ]:
import numpy as np
a = np.zeros((5,))
print(a)

[0. 0. 0. 0. 0.]


In [ ]:
import numpy as np
b = np.ones((5,))
print(b)

[1. 1. 1. 1. 1.]


## 建立多維陣列

In [ ]:
import numpy as np
listdata = [[1,2,3,4,5],
       [6,7,8,9,10]]
na = np.array(listdata)
print(na)
print('維度', na.ndim)
print('形狀', na.shape)
print('數量', na.size)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
維度 2
形狀 (2, 5)
數量 10


## 改變陣列形狀：reshape()

In [ ]:
import numpy as np
adata = np.arange(1,17)
print(adata)
bdata = adata.reshape(4,4)
print(bdata)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


## 一維陣列取值

In [ ]:
import numpy as np
na = np.arange(0,6)
print(na)
print(na[0])
print(na[5])
print(na[1:5])
print(na[1:5:2])
print(na[5:1:-1])
print(na[:])
print(na[:3])
print(na[3:])

[0 1 2 3 4 5]
0
5
[1 2 3 4]
[1 3]
[5 4 3 2]
[0 1 2 3 4 5]
[0 1 2]
[3 4 5]


## 多維陣列取值

In [ ]:
import numpy as np
na = np.arange(1, 17).reshape(4, 4)
na

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
na[2, 3]

12

In [ ]:
print(na[1, 1:3])			#[6,7]
print(na[1:3, 2])			#[7,11]
print(na[1:3, 1:3])		#[[6,7],[7,11]]
print(na[::2, ::2])		#[[1,3],[9,11]]
print(na[:, 2])				#[3,7,11,15]
print(na[1, :])				#[5,6,7,8]
print(na[:, :])				#矩陣全部

[6 7]
[ 7 11]
[[ 6  7]
 [10 11]]
[[ 1  3]
 [ 9 11]]
[ 3  7 11 15]
[5 6 7 8]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


## 產生隨機資料:np.ramdom()

In [ ]:
import numpy as np
print('1.產生2x3 0~1之間的隨機浮點數\n',
      np.random.rand(2,3))
print('2.產生2x3常態分佈的隨機浮點數\n',
      np.random.randn(2,3))
print('3.產生0~4(不含5)隨機整數\n',
      np.random.randint(5))
print('4.產生2~4(不含5)5個隨機整數\n',
      np.random.randint(2,5,[5]))
print('5.產生3個 0~1之間的隨機浮點數\n',
      np.random.random(3),'\n',
      np.random.random_sample(3),'\n',
      np.random.sample(3))

1.產生2x3 0~1之間的隨機浮點數
 [[0.94329398 0.02171785 0.93177655]
 [0.07233092 0.22129355 0.87224119]]
2.產生2x3常態分佈的隨機浮點數
 [[-2.4608004   0.26916451  1.20200225]
 [-1.00016318  0.78986006  0.17624573]]
3.產生0~4(不含5)隨機整數
 1
4.產生2~4(不含5)5個隨機整數
 [3 2 2 3 4]
5.產生3個 0~1之間的隨機浮點數
 [0.01449087 0.50213467 0.40689873] 
 [0.19960448 0.31882974 0.47923504] 
 [0.75353886 0.43912385 0.08078347]


## Numpy讀取CSV 檔案

In [ ]:
import numpy as np
na = np.genfromtxt('scores.csv', delimiter=',', skip_header=1)
print(na.shape)

(30, 4)


## Numpy陣列運算

In [ ]:
import numpy as np
a = np.arange(1,10).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
print('a 陣列內容：\n', a)
print('b 陣列內容：\n', b)

a 陣列內容：
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
b 陣列內容：
 [[10 11 12]
 [13 14 15]
 [16 17 18]]


In [ ]:
print('a 陣列元素都加值：\n', a + 1)

a 陣列元素都加值：
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [ ]:
print('a 陣列元素都平方：\n', a ** 2)

a 陣列元素都平方：
 [[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [ ]:
print('a 陣列元素加判斷：\n', a < 5)

a 陣列元素加判斷：
 [[ True  True  True]
 [ True False False]
 [False False False]]


In [ ]:
print('a 陣列取出第一個row都加1：\n', a[0,:] + 1)
print('a 陣列取出第一個col都加1：\n', a[:,0] + 1)

a 陣列取出第一個row都加1：
 [2 3 4]
a 陣列取出第一個col都加1：
 [2 5 8]


In [ ]:
print('a b 陣列對應元素相加：\n', a + b)
print('a b 陣列對應元素相乘：\n', a * b)

a b 陣列對應元素相加：
 [[11 13 15]
 [17 19 21]
 [23 25 27]]
a b 陣列對應元素相乘：
 [[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]


In [ ]:
print('a b 陣列內積計算：\n', np.dot(a,b))

a b 陣列內積計算：
 [[ 84  90  96]
 [201 216 231]
 [318 342 366]]


## Numpy常用的計算及統計函式

In [ ]:
import numpy as np
a = np.arange(1,10).reshape(3,3)
print('陣列的內容：\n', a)
print('1.最小值與最大值：\n',
      np.min(a), np.max(a))
print('2.每一直行最小值與最大值：\n',
      np.min(a, axis=0), np.max(a, axis=0))
print('3.每一橫列最小值與最大值：\n',
      np.min(a, axis=1), np.max(a, axis=1))
print('4.加總、乘積及平均值：\n',
      np.sum(a), np.prod(a), np.mean(a))
print('5.每一直行加總、乘積與平均值：\n',
      np.sum(a, axis=0), np.prod(a, axis=0), np.mean(a, axis=0))
print('6.每一橫列加總、乘積與平均值：\n',
      np.sum(a, axis=1), np.prod(a, axis=1), np.mean(a, axis=1))

陣列的內容：
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
1.最小值與最大值：
 1 9
2.每一直行最小值與最大值：
 [1 2 3] [7 8 9]
3.每一橫列最小值與最大值：
 [1 4 7] [3 6 9]
4.加總、乘積及平均值：
 45 362880 5.0
5.每一直行加總、乘積與平均值：
 [12 15 18] [ 28  80 162] [4. 5. 6.]
6.每一橫列加總、乘積與平均值：
 [ 6 15 24] [  6 120 504] [2. 5. 8.]


In [ ]:
import numpy as np
a = np.random.randint(100,size=50)
print('陣列的內容：', a)
print('1.標準差：', np.std(a))
print('2.變異數：', np.var(a))
print('3.中位數：', np.median(a))
print('4.百分比值：', np.percentile(a, 80))
print('5.最大最小差值：', np.ptp(a))

陣列的內容： [38 66 31 74 31  6 66 33 79 59 34 35 82 59 31 75 28 48 38 85 78 11 79 89
 33 14 61  9 85 92 90 42 43 78 23 25 57 92 30 95 90 37  3 94 16 34 17 12
 65 52]
1.標準差： 27.82490970335753
2.變異數： 774.2256
3.中位數： 45.5
4.百分比值： 79.60000000000001
5.最大最小差值： 92


## Numpy的排序

In [ ]:
import numpy as np
a = np.random.choice(50, size=10, replace=False)
print('排序前的陣列：', a)
print('排序後的陣列：', np.sort(a))
print('排序後的索引：', np.argsort(a))
#用索引到陣列取值
for i in np.argsort(a):
    print(a[i], end=',')

排序前的陣列： [24  6  3 12 11 37 26  5  4 35]
排序後的陣列： [ 3  4  5  6 11 12 24 26 35 37]
排序後的索引： [2 8 7 1 4 3 0 6 9 5]
3,4,5,6,11,12,24,26,35,37,

In [ ]:
import numpy as np
a = np.random.randint(0,10,(3,5))
print('原陣列內容：')
print(a)
print('將每一直行進行排序：')
print(np.sort(a, axis=0))
print('將每一橫列進行排序：')
print(np.sort(a, axis=1))

原陣列內容：
[[9 2 9 2 2]
 [5 5 6 9 7]
 [3 8 7 8 3]]
將每一直行進行排序：
[[3 2 6 2 2]
 [5 5 7 8 3]
 [9 8 9 9 7]]
將每一橫列進行排序：
[[2 2 2 9 9]
 [5 5 6 7 9]
 [3 3 7 8 8]]
